const skills = [
  "react.svg",
  "nextjs.svg",
  "js.svg",
  "typescript.png",
  "html.svg",
  "css.svg",
  "tailwind.svg",
  "materialUI.png",
  "framer-motion.svg",
  "nodejs.svg",
  "express.svg",
  "python.svg",
  "bootstrap.svg",
  "git.svg",
  "github.svg",
  "linux.svg",
  "docker.png",
  "redux.png",
  "reduxSaga.png",
  "reduxThunk.png",
  "salesforce.png",
  "sql.png",
  "mongodb.svg",
  "firebase.svg",
  "aws.png",
  "azure.png"
]; // Add or remove skills here, make sure to include the image respective to the skill inside the public/skills folder and use the correct file extension

export default skills;
